### ISSUE TITLE
Error on Front End (Multiple relations)

### ISSUE THREAD

**Issue by jjeshta** [lsldigital/gocipe#33]
Entities having multiple relationships with another entity is being bugged on the front side.
It happens when the referenced entity is selected. (select box)
It does not take multiple relationships into consideration on front.

Error: 
```
vue.runtime.esm.js?2b0e:1737 TypeError: this$1.entity.set[ReferencedEntity]id is not a function
```

**Comment by JulesMike** [comment]
#39
